
#ifndef PROJECTRESOURCETYPE_H_
#define PROJECTRESOURCETYPE_H_

namespace nextar {

enum ProjectResourceType {
	RESOURCE_MESH,
	RESOURCE_TEXTURE,
	RESOURCE_RENDERSYS,
	RESOURCE_MATERIAL,
	RESOURCE_SHADER,
	RESOURCE_SCRIPT_RENDERSYS,
	RESOURCE_SCRIPT_MATERIAL,
	RESOURCE_SCRIPT_SHADER,
	RESOURCE_UNKNOWN,
	RESOURCE_TYPE_COUNT,
};

}

#endif //PROJECTRESOURCETYPE_H_
