/*
 * ScriptStrings.h
 *
 *  Created on: 19-May-2014
 *      Author: obhi
 */
#ifdef SCRIPT_STRING
#	undef SCRIPT_STRING
#endif

#if defined(NEX_SHADER_STRINGS_DEFINE)
#define SCRIPT_STRING(str, what)	const char* SCRIPT_##str=what
#else
#define SCRIPT_STRING(str, what)	extern const char* SCRIPT_##str
#endif
#ifndef _SS
#	define _SS(str) SCRIPT_##str
#endif

namespace ShaderScript {
// ## commands
SCRIPT_STRING(PROGRAM_SCRIPT, "script");
SCRIPT_STRING(REGION_SHADER, "effect");
SCRIPT_STRING(CMD_SHADER, "shader");
SCRIPT_STRING(CMD_PASS, "pass");
SCRIPT_STRING(CMD_FLAGS, "flags");
SCRIPT_STRING(CMD_BLEND_STATE, "blend-state");
SCRIPT_STRING(CMD_CBUFFER, "cbuffer");
SCRIPT_STRING(CMD_VAR, "var");
SCRIPT_STRING(CMD_CONTEXT, "context");
SCRIPT_STRING(CMD_DEPTH_STENCIL_STATE, "depth-stencil-state");
SCRIPT_STRING(CMD_RASTER_STATE, "raster-state");
SCRIPT_STRING(CMD_TEXTURE_STATE, "texture-state");
SCRIPT_STRING(CMD_PROGRAM, "program");
SCRIPT_STRING(CMD_BLEND, "blend");
SCRIPT_STRING(CMD_TARGET, "target");
SCRIPT_STRING(CMD_DEPTH_STATE, "depth-state");
SCRIPT_STRING(CMD_STENCIL_BACK_OP, "stencil-back");
SCRIPT_STRING(CMD_STENCIL_FRONT_OP, "stencil-front");
SCRIPT_STRING(CMD_STENCIL_TEST, "stencil-test");
SCRIPT_STRING(CMD_ANTI_ALIASING, "anti-aliasing");
SCRIPT_STRING(CMD_DEPTH_BIAS, "depth-bias");
SCRIPT_STRING(CMD_DEPTH_CLIP, "depth-clip");
SCRIPT_STRING(CMD_RASTER, "raster");
SCRIPT_STRING(CMD_SCISSOR, "scissor");
SCRIPT_STRING(CMD_FRAGMENT_PROG, "fragment-program");
SCRIPT_STRING(CMD_GEOMETRY_PROG, "geometry-program");
SCRIPT_STRING(CMD_VERTEX_PROG, "vertex-program");
SCRIPT_STRING(CMD_HULL_PROG, "hull-program");
SCRIPT_STRING(CMD_DOMAIN_PROG, "domain-program");
SCRIPT_STRING(CMD_OPTION, "option");
SCRIPT_STRING(CMD_DEFINE, "define");
SCRIPT_STRING(CMD_UNIT, "unit");
SCRIPT_STRING(CMD_SAMPLER, "sampler");
SCRIPT_STRING(CMD_MIN_FILTER, "min-filter");
SCRIPT_STRING(CMD_MAG_FILTER, "min-filter");
SCRIPT_STRING(CMD_ADDRESS_U, "address-u");
SCRIPT_STRING(CMD_ADDRESS_V, "address-v");
SCRIPT_STRING(CMD_ADDRESS_W, "address-w");
SCRIPT_STRING(CMD_ANISOTROPY, "anisotropy");
SCRIPT_STRING(CMD_MIN_LOD, "min-lod");
SCRIPT_STRING(CMD_MAX_LOD, "max-lod");
SCRIPT_STRING(CMD_LOD_BIAS, "lod-bias");
SCRIPT_STRING(CMD_BORDER_COLOR, "border-color");
SCRIPT_STRING(CMD_COMPARE, "compare");
// ## parameters

// ## arguments
SCRIPT_STRING(ARG_ALWAYS, "always");
SCRIPT_STRING(ARG_EQUAL, "equal");
SCRIPT_STRING(ARG_GREATER, "greater");
SCRIPT_STRING(ARG_GREATER_EQUAL, "greater-equal");
SCRIPT_STRING(ARG_LESS, "less");
SCRIPT_STRING(ARG_LESS_EQUAL, "less-equal");
SCRIPT_STRING(ARG_NEVER, "never");
SCRIPT_STRING(ARG_NOT_EQUAL, "not-equal");
SCRIPT_STRING(ARG_DECREMENT, "decrement");
SCRIPT_STRING(ARG_DECREMENT_SATURATE, "decrement-saturate");
SCRIPT_STRING(ARG_INCREMENT, "increment");
SCRIPT_STRING(ARG_INCREMENT_SATURATE, "increment-saturate");
SCRIPT_STRING(ARG_INVERT, "invert");
SCRIPT_STRING(ARG_KEEP, "keep");
SCRIPT_STRING(ARG_REPLACE, "replace");
SCRIPT_STRING(ARG_ZERO, "zero");
SCRIPT_STRING(ARG_ONE, "one");
SCRIPT_STRING(ARG_DEST_ALPHA, "dest-alpha");
SCRIPT_STRING(ARG_DEST_COLOR, "dest-color");
SCRIPT_STRING(ARG_INV_DEST_ALPHA, "inv-dest-alpha");
SCRIPT_STRING(ARG_INV_DEST_COLOR, "inv-dest-color");
SCRIPT_STRING(ARG_SRC_ALPHA, "src-alpha");
SCRIPT_STRING(ARG_SRC_COLOR, "src-color");
SCRIPT_STRING(ARG_INV_SRC_ALPHA, "inv-src-alpha");
SCRIPT_STRING(ARG_INV_SRC_COLOR, "inv-src-color");
SCRIPT_STRING(ARG_ADD, "add");
SCRIPT_STRING(ARG_INV_SUB, "inv-sub");
SCRIPT_STRING(ARG_MAX, "max");
SCRIPT_STRING(ARG_MIN, "min");
SCRIPT_STRING(ARG_SUB, "sub");
SCRIPT_STRING(ARG_SOLID, "solid");
SCRIPT_STRING(ARG_WIRE, "wire");
SCRIPT_STRING(ARG_POINT, "point");
SCRIPT_STRING(ARG_FRONT, "front");
SCRIPT_STRING(ARG_BACK, "back");
SCRIPT_STRING(ARG_NONE, "none");
SCRIPT_STRING(ARG_ALL, "all");
SCRIPT_STRING(ARG_LINEAR, "linear");
SCRIPT_STRING(ARG_LINEAR_MIP_LINEAR, "linear-mip-linear");
SCRIPT_STRING(ARG_LINEAR_MIP_NEAREST, "linear-mip-nearest");
SCRIPT_STRING(ARG_NEAREST, "nearest");
SCRIPT_STRING(ARG_NEAREST_MIP_LINEAR, "nearest-mip-linear");
SCRIPT_STRING(ARG_NEAREST_MIP_NEAREST, "nearest-mip-nearest");
SCRIPT_STRING(ARG_BORDER, "border");
SCRIPT_STRING(ARG_CLAMP, "clamp");
SCRIPT_STRING(ARG_MIRROR, "mirror");
SCRIPT_STRING(ARG_REPEAT, "repeat");
SCRIPT_STRING(ARG_DEFERRED_LIGHTING, "deferred-lighting");
SCRIPT_STRING(ARG_BACKGROUND, "background");
SCRIPT_STRING(ARG_BASIC_DEFERRED, "basic-deferred");
SCRIPT_STRING(ARG_FORWARD, "forward");
SCRIPT_STRING(ARG_DEBUG, "debug");
SCRIPT_STRING(ARG_OVERLAY, "overlay");
SCRIPT_STRING(ARG_POST_FX, "compositor");
SCRIPT_STRING(ARG_TRANSLUCENT, "translucent");
SCRIPT_STRING(ARG_UNKNOWN, "unknown");
SCRIPT_STRING(ARG_FRAME, "frame");
SCRIPT_STRING(ARG_VIEW, "view");
SCRIPT_STRING(ARG_PASS, _SS(CMD_PASS));
SCRIPT_STRING(ARG_MATERIAL, "material");
SCRIPT_STRING(ARG_OBJECT, "object");
SCRIPT_STRING(ARG_NO_COMMON, "no-common");
SCRIPT_STRING(ARG_WIREFRAME, "wireframe");
SCRIPT_STRING(ARG_NO_CULL, "no-cull");

// ## Tags
SCRIPT_STRING(TAG_UI, "ui");
SCRIPT_STRING(TAG_DESC, "desc");
SCRIPT_STRING(TAG_WHEN, "when");
SCRIPT_STRING(TAG_CONTEXT, _SS(CMD_CONTEXT));
// ## Regions
SCRIPT_STRING(REG_CBUFFER, _SS(CMD_CBUFFER));
SCRIPT_STRING(REG_DEFINE, _SS(CMD_DEFINE));
SCRIPT_STRING(REG_PREDEFS, "predefs");
SCRIPT_STRING(REG_PREFIX, "prefix");
// ## Auto param semantics
SCRIPT_STRING(ARG_INV_PROJECTION, "INVPROJECTION");
SCRIPT_STRING(ARG_OBJECT_TRANSFORM, "OBJECTTRANSFORM");
SCRIPT_STRING(ARG_OMNI_LIGHT_PROPERTIES, "OMNILIGHTPROPERTIES");
SCRIPT_STRING(ARG_DEPTH_MAP, "DEPTHMAP");
SCRIPT_STRING(ARG_NORMAL_MAP, "NORMALMAP");
SCRIPT_STRING(ARG_ALBEDO_MAP, "ALBEDOMAP");
SCRIPT_STRING(ARG_SPECULAR_AND_GLOSS_MAP, "SPECULARANDGLOSSMAP");
SCRIPT_STRING(ARG_MODEL_VIEW_PROJECTION, "MODELVIEWPROJECTION");
SCRIPT_STRING(ARG_DIFFUSE_COLOR, "DIFFUSECOLOR");
SCRIPT_STRING(ARG_CONSTANT_SCALE_FACTOR, "CONSTANTSCALEFACTOR");
SCRIPT_STRING(ARG_SKY_LIGHT, "SKYLIGHT");
// ## Values
SCRIPT_STRING(VAL_DISABLE, "disable");
SCRIPT_STRING(VAL_ADVANCED, "advanced");
SCRIPT_STRING(VAL_DEFAULT, "default");

}
